### PR TITLE
Show JSON values nicely

### PR DESCRIPTION
**Pull request by ghost**
*    https://github.com/Open-Telecoms-Data/cove-ofds/issues/20
*    https://github.com/Open-Telecoms-Data/cove-ofds/issues/13

### CODE REVIEW

**Comment by ghost** [comment]
@lgs85 @duncandewhurst Can you review this one on dev server?

Basically anywhere we show JSON values - JSON schema checks, python checks, additional fields checks - it's going through a new template system. This puts " around strings, makes lists actually be lists and makes long lists hidden by default.

Can you check and make sure this looks good, and there aren't unintended side affects?

(The style of show hide links doesn't look great, but it looks like the other ones we currently have and that's already being dealt with in #65 )


JV1
JV3
JV2
JV4

**Comment by duncandewhurst** [comment]
Please can you share a link to the dev site?

Looking at the screenshots:

* Value column is missing from the results for 'value does not match any codes':
image
* Value column for node location coordinates should show the raw JSON value, rather than a formatted list:
image

Otherwise, looks good!

**Comment by ghost** [comment]
> Please can you share a link to the dev site?

Messaged

> Value column is missing from the results for 'value does not match any codes':

Whoops, a one character typo got in - will be fixed here or in another PR

> Value column for node location coordinates should show the raw JSON value, rather than a formatted list:

If we are saying there should be exceptions to trying to show JSON values nicely, can we be clear about what they are? 

* eg If Node Location Coordinates is one exception, is Span  Location Coordinates another?
* eg are we sure? A spans location coordinates ending up in a node by mistake could have a very long list, and elsewhere we have said long lists should be hidden by default which makes sense

**Comment by duncandewhurst** [comment]
> If we are saying there should be exceptions to trying to show JSON values nicely, can we be clear about what they are?

If we're showing a JSON value from the **data**, then we should show it 'raw', i.e. not formatted as a bulleted list. It would still be good to hide/collapse long values, but not to format them. If we're showing a JSON value from the **schema** (like an enum) then I think it's OK to format that as a bulleted list. I didn't realise that the list of codes was a JSON value.

>     * eg If Node Location Coordinates is one exception, is Span  Location Coordinates another?

Yes.

>     * eg are we sure? A spans location coordinates ending up in a node by mistake could have a very long list, and elsewhere we have said long lists should be hidden by default which makes sense

Hiding it would be good, but not formatting it as a bulleted list.

**Comment by ghost** [comment]
I think some discussion would be good. I'm not clear how we would hide/collapse long values without some kind of formatting and if strings should still be shown quoted (I'm guessing yes, but technically showing raw would mean no).

(I suspect this one is going to take more time to sort out than I have left in the sprint, sorry.)

**Comment by ghost** [comment]
Try to get this in: Just have quotes around strings, leave lists as raw JSON and don't try and collapse them.

**Comment by ghost** [comment]
@duncandewhurst @lgs85 Please review and if you are happy pass to @Lathrisk for code review, then merge

**Comment by duncandewhurst** [comment]
Looks good to me, but I think I missed the opportunity for @Lathrisk to review!

**Review by codemacabre — APPROVED** [review]

**Pull request merged**
