### PR TITLE
schema: Update links to point to latest

### PR DESCRIPTION
**Pull request by ghost**
https://github.com/Open-Telecoms-Data/cove-ofds/issues/34

### CODE REVIEW

**Comment by ghost** [comment]
@lgs85 @duncandewhurst Unfortunately, you'll need to check every link by hand and fix some. I tried at random the one in the download data box and it's now broken. Old: https://open-fibre-data-standard.readthedocs.io/en/latest/reference/publication_formats.html  New: https://open-fibre-data-standard.readthedocs.io/en/latest/reference/publication_formats/index.html  Is this expected? 

If so you could list changes needed on this PR, or even do a commit yourself and add to this PR before sending to a dev.

**Comment by lgs85** [comment]
>I tried at random the one in the download data box and it's now broken. Old: https://open-fibre-data-standard.readthedocs.io/en/latest/reference/publication_formats.html New: https://open-fibre-data-standard.readthedocs.io/en/latest/reference/publication_formats/index.html Is this expected?

Yes, this reflects a change to the docs. @duncandewhurst we should add some documentation somewhere to make sure we pick up on these.

**Comment by duncandewhurst** [comment]
I used `grep /latest/ *` in `cove_ofds/templates/cove_ofds` to find and check all the URLs. I've fixed the broken URLs in https://github.com/Open-Telecoms-Data/cove-ofds/pull/38/commits/13309ca7290f5a0f2271e8b80d969422b4a4b0a6.

I think I've resolved the merge conflict correctly, but please check!

> @duncandewhurst we should add some documentation somewhere to make sure we pick up on these.

Already noted in https://github.com/Open-Telecoms-Data/standard-development-handbook/issues/21, great minds etc. etc.

**Review by Lathrisk — APPROVED** [review]
LGTM, I didn't test all the links but I did grab a few at random and they all seem to link correctly.

**Review by codemacabre — APPROVED** [review]
Checked several links and they LGTM

**Comment by ghost** [comment]
This was a small change so I merged it. Have verified it's on live fine.

**Pull request merged**
