### PR TITLE
2023 06 27

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ghost** [comment]
@duncandewhurst Can you check UI?

ad prop ui

**Review by Bjwebb — DISMISSED** [review]

**Comment by duncandewhurst** [comment]
Can we add the actual field/property name to the path or put it in another column? I don't mind which, but as it stands, the user can't actually see the name of the property that they need to remove. Otherwise, looks good!

**Comment by ghost** [comment]
ad prop ui 2

@duncandewhurst Is this ok as a first go and we can tweak later? This PR also fixes another bug so it's good to get in.

**Review by Bjwebb — APPROVED** [review]

**Comment by duncandewhurst** [comment]
Looks good to me!

**Pull request merged**
